### ISSUE TITLE
Vẽ, thiết kế Class Diagram tổng thể cho đề tài

### ISSUE THREAD

**Issue by AnNgoIT** [AnNgoIT/Camera_Dashboard_Group03_TOEN#10]
- [x] Tìm hiểu cấu trúc Class của các đối tượng
- [x] Thiết kế các Class
- [x] Xây dựng các mối quan hệ cho các Class
- [x] Vẽ Class Diagram

**Comment by truong-ne** [comment]
20.03.2023: Tìm hiểu và chuẩn bị cho yêu cầu

**Comment by AnNgoIT** [comment]
Đã tìm hiểu cấu trúc Class của các đối tượng 

[PhanthichhethongCamera.docx](https://github.com/AnNgoIT/Camera_Dashboard_Group03_TOEN/files/11058660/PhanthichhethongCamera.docx)

**Comment by AnNgoIT** [comment]
Đã thiết kế các Class

[def_Class.pptx](https://github.com/AnNgoIT/Camera_Dashboard_Group03_TOEN/files/11058997/def_Class.pptx)

**Comment by tuannguyennocode** [comment]
Đã xây dựng các mối quan hệ cho class
https://drive.google.com/file/d/1U66RXtq7zY_Hfop_RKn5KaiWbddPE4nZ/view?usp=sharing
