### ISSUE TITLE
Vẽ Activity Diagram cho các Usecase: Đăng ký; Đăng nhập; Quản lý camera; Theo dõi camera

### ISSUE THREAD

**Issue by AnNgoIT** [AnNgoIT/Camera_Dashboard_Group03_TOEN#13]
- [x] Vẽ Activity Diagram cho usecase Đăng ký
- [x] Vẽ Activity Diagram cho usecase Đăng nhập
- [x] Vẽ Activity Diagram cho usecase Quản lý camera
- [x] Vẽ Activity Diagram cho usecase Theo dõi camera

**Comment by truong-ne** [comment]
https://docs.google.com/document/d/1WgQ69ufs8m0ZOQGkZKXlJlzLeHZAHiGP/edit?usp=sharing&ouid=109019883761453819163&rtpof=true&sd=true
