### ISSUE TITLE
Vẽ Activity Diagram cho các Usecase: Quản lý tài khoản người dùng; Quản lý dữ liệu; Quản lý hệ thống

### ISSUE THREAD

**Issue by AnNgoIT** [AnNgoIT/Camera_Dashboard_Group03_TOEN#15]
- [x] Vẽ Activity Diagram cho usecase Xóa tài khoản người dùng
- [x] Vẽ Activity Diagram cho usecase Thay đổi dữ liệu
- [x] Vẽ Activity Diagram cho usecase Thay đổi trạng thái camera

**Comment by tuannguyennocode** [comment]
https://drive.google.com/file/d/1zfDUe1qz4u3X_EKGWWYZ84PUSViDGsJ9/view?usp=sharing

**Comment by tuannguyennocode** [comment]
https://drive.google.com/file/d/1t_uYSS8nDgT6tbAeceepRqRoXvwbc_7Y/view?usp=share_link

**Comment by tuannguyennocode** [comment]
https://drive.google.com/file/d/1UoFu21ZbeqUpZhcM-_gNWxd1Vm1eJ0eh/view?usp=sharing
Hoàn thành Vẽ Activity Diagram cho usecase Thay đổi dữ liệu
