### ISSUE TITLE
Triển khai testing tool cho project

### ISSUE THREAD

**Issue by AnNgoIT** [AnNgoIT/Camera_Dashboard_Group03_TOEN#16]
- [x] Triển khai Testing Tool (Cypress) cho dự án
- [x] Lên kế hoạch test cho các chức năng trong dự án
- [ ] Tạo một vài test case cho các chức năng, sau tiến hành chạy test

**Comment by AnNgoIT** [comment]
Đã triển khai Testing Tool cho dự án
Đã lập kế hoạch test cho các chức năng trong dự án
Đã tạo một vài test case cho các chức năng, sau đó tiến hành chạy test

**Comment by tuannguyennocode** [comment]
Đã cài đặt triển khai công cụ Cypress

**Comment by tuannguyennocode** [comment]
![Image](https://user-images.githubusercontent.com/92933032/229476291-d5256cb4-b71f-40a4-9e19-f68bf39fa982.png)

**Comment by AnNgoIT** [comment]
Link triển khai testing tool (Cypress) cho project:
https://github.com/AnNgoIT/Camera_Dashboard_Group03_TOEN.git

**Comment by truong-ne** [comment]
Triển khai api để dùng testing tool
https://github.com/AnNgoIT/Camera_Dashboard_Group03_TOEN.git

**Comment by truong-ne** [comment]
![image](https://user-images.githubusercontent.com/118288031/229480470-adabea7d-0223-4d93-a5b3-34ce6ea1e0b4.png)
