### ISSUE TITLE
Viết Flow of events cho các Usecase Đăng ký, Đăng nhập, Quản lý Camera, Theo dõi Camera

### ISSUE THREAD

**Issue by AnNgoIT** [AnNgoIT/Camera_Dashboard_Group03_TOEN#17]
- [x] Viết Flow of events cho usecase Đăng ký
- [x] Viết Flow of events cho usecase Đăng nhập
- [x] Viết Flow of events cho usecase Quản lý Camera
- [x] Viết Flow of events cho usecase Theo dõi Camera

**Comment by truong-ne** [comment]
https://docs.google.com/document/d/1xTYgKonAYXfX7Q8O6g60j6U105xlVeAF/edit?usp=sharing&ouid=109019883761453819163&rtpof=true&sd=true
