### ISSUE TITLE
Hoàn thiện Use-case diagram cho toàn bộ các chức năng trên giao diện sau khi được thầy thầy góp ý

### ISSUE THREAD

**Issue by AnNgoIT** [AnNgoIT/Camera_Dashboard_Group03_TOEN#18]
- [x] Xác định lai chính xác các actor của hệ thống
- [x] Xác định lại một cách chính sác các yêu cầu chức năng, phi chức năng của hệ thống
- [x] Xác định các Use-case cho hệ thống
- [x] Vẽ Use-case tổng quan cho hệ thống
- [x] Căn chỉnh Use-case theo đặc tả đề tài

**Comment by AnNgoIT** [comment]
Link Use-case:  https://drive.google.com/file/d/1UaWmOPPg2q7GwtIhf8b8XRMVv-KG5sjF/view?usp=sharing

**Comment by tuannguyennocode** [comment]
Link Use-case: https://drive.google.com/file/d/1UaWmOPPg2q7GwtIhf8b8XRMVv-KG5sjF/view?usp=sharing

**Comment by AnNgoIT** [comment]
Link xác định actor, chức năng, use-case: 
https://drive.google.com/file/d/1B4EBISMsoksmImpLOKzO6stRIcsl9XVL/view?usp=sharing

**Comment by tuannguyennocode** [comment]
Link xác định actor, chức năng, use-case:
https://drive.google.com/file/d/1B4EBISMsoksmImpLOKzO6stRIcsl9XVL/view?usp=sharing

**Comment by truong-ne** [comment]
Link Use-case: https://drive.google.com/file/d/1UaWmOPPg2q7GwtIhf8b8XRMVv-KG5sjF/view?usp=sharing
Link xác định actor, chức năng, use-case: https://drive.google.com/file/d/1B4EBISMsoksmImpLOKzO6stRIcsl9XVL/view?usp=sharing
