### ISSUE TITLE
Tìm hiểu đề tài

### ISSUE THREAD

**Issue by AnNgoIT** [AnNgoIT/Camera_Dashboard_Group03_TOEN#2]
- [x] Truy cập và xem qua figma được cung cấp: https://www.figma.com/file/xwihQlHv0pFyVdpNaqqONH/Figma-AI-Camera-Admin-Dashboard-UI?node-id=0%3A1
- [x] Tìm hiểu kĩ yêu cầu của đề tài
- [x] Xác định được các chức năng cần thiết của đề tài

**Comment by truong-ne** [comment]
Đã xác định được cách vận hành và chức năng của đề tài.

**Comment by tuannguyennocode** [comment]
Đã truy cập và xem figma

**Comment by tuannguyennocode** [comment]
Đã tìm hiểu yêu cầu của đề tài

**Comment by tuannguyennocode** [comment]
Đã xác định được các chức năng cần thiết của đề tài
