### ISSUE TITLE
Vẽ, thiết kế Class Diagram chi tiết, rõ ràng cho đề tài

### ISSUE THREAD

**Issue by AnNgoIT** [AnNgoIT/Camera_Dashboard_Group03_TOEN#20]
- [x] Xác định kỹ các mối quan hệ giữa các class
- [x] Xác định các thuộc tính, phương thức,... trong  Class Diagram một cách rõ ràng
- [x] Vẽ lại chi tiết, hoàn chỉnh Class Diagram
- [x] Viết document trình bày cụ thể về Class Diagram cho đề tài

**Comment by AnNgoIT** [comment]
Link Class Diagram: https://drive.google.com/file/d/1r_Ih4-dRUlWP28WZiV6bI0ZqTuJhpW8l/view?usp=sharing

**Comment by tuannguyennocode** [comment]
Link Class Diagram: https://drive.google.com/file/d/1r_Ih4-dRUlWP28WZiV6bI0ZqTuJhpW8l/view?usp=sharing
