### ISSUE TITLE
Hoàn thiện các flow of events, Activity Diagram cho các Use-case

### ISSUE THREAD

**Issue by AnNgoIT** [AnNgoIT/Camera_Dashboard_Group03_TOEN#21]
- [x] Xem lại các flow of events của các Use-case đã đúng hay chưa, nếu chưa đúng thì chỉnh lại
- [x] Hoàn thiện các flow of events, Activity Diagram chưa hoàn thành
- [x] Các flows of events, Activity Diagram phải tuuan theo các Use-case và đặc tả đề tài

**Comment by tuannguyennocode** [comment]
https://docs.google.com/document/d/18M_uNnfUWFIAjFCTEQrtmncITjgOhYCs/edit?usp=sharing&ouid=105777061656077981289&rtpof=true&sd=true

**Comment by tuannguyennocode** [comment]
https://docs.google.com/document/d/1TH1YLhG0CCWGG6EPgQmtDMG34ZGOmoMe/edit?usp=sharing&ouid=105777061656077981289&rtpof=true&sd=true
Activity Diagram

**Comment by truong-ne** [comment]
Flow of Events:
https://docs.google.com/document/d/1xTYgKonAYXfX7Q8O6g60j6U105xlVeAF/edit?usp=sharing&ouid=109019883761453819163&rtpof=true&sd=true
Activity Diagram:
https://docs.google.com/document/d/1WgQ69ufs8m0ZOQGkZKXlJlzLeHZAHiGP/edit?usp=sharing&ouid=109019883761453819163&rtpof=true&sd=true

**Comment by AnNgoIT** [comment]
Link các Flow of Events (Quản lý cảnh báo, Quản lý khu vực, Thống kê):
https://docs.google.com/document/d/1tAA8VXCOoAAJ0dqbowBDx8Hc7sd7h37CBuJH9P3FzDA/edit?usp=sharing

**Comment by AnNgoIT** [comment]
Link các Activity Diagram (Quản lý cảnh báo, Quản lý khu vực, thống kê):
https://docs.google.com/document/d/1LH4WEfuR3Leg7QOsq42BN2reO8v4nKpqM4uJ5FW4udk/edit?usp=sharing
