### ISSUE TITLE
Hoàn thiện triển khai testing tool + Lên kế hoạch và viết các test case (giao diện, chức năng) cho đề tài

### ISSUE THREAD

**Issue by AnNgoIT** [AnNgoIT/Camera_Dashboard_Group03_TOEN#22]
- [x] Hoàn thành công việc của tuần trước chưa làm xong về Triển khai testing tool cho project
- [x] Lên kế hoạch viết test case giao diện
- [x] Lên kế hoạch viết test case chức năng
- [x] (Trường) Viết test case giao diện + chức năng cho trang Login 
- [x] (Tuấn) Viết test case giao diện + chức năng cho trang Trang chủ
- [x] (Ân) Viết test case giao diện + chức năng cho trang Quản lý Camera
- [x] Upload các kết quả làm được lên repository chung của nhóm: https://github.com/AnNgoIT/Camera_Dashboard_Group03_TOEN.git

**Comment by truong-ne** [comment]
api dùng để test: https://user-management-mu.vercel.app/

**Comment by AnNgoIT** [comment]
Link triển khai testing tool (Cypress) cho project:
https://github.com/AnNgoIT/Camera_Dashboard_Group03_TOEN.git
