### ISSUE TITLE
Viết test case cho trang Đăng nhập

### ISSUE THREAD

**Issue by AnNgoIT** [AnNgoIT/Camera_Dashboard_Group03_TOEN#26]
- [x] Phân tích giao diện trang Đăng nhập
- [x] Xây dựng kế hoạch test trang Đăng nhập
- [x] Viết test case giao diện trang Đăng nhập

**Comment by truong-ne** [comment]
![Image](https://user-images.githubusercontent.com/118288031/230874614-cd7fb166-c363-4d7e-a523-9c435d015547.png)
