### ISSUE TITLE
Viết test case cho trang Thống kê

### ISSUE THREAD

**Issue by AnNgoIT** [AnNgoIT/Camera_Dashboard_Group03_TOEN#31]
- [x] Phân tích giao diện trang Thống kê
- [x] Xây dựng kế hoạch test trang Thống kê
- [x] Viết test case giao diện trang Thống kê

**Comment by truong-ne** [comment]
![Image](https://user-images.githubusercontent.com/118288031/230877613-b00c5391-3ada-48e7-b0c7-21ebbcfdd945.png)
