### ISSUE TITLE
Viết test case cho trang Đăng kí

### ISSUE THREAD

**Issue by AnNgoIT** [AnNgoIT/Camera_Dashboard_Group03_TOEN#32]
- [x] Phân tích giao diện trang Đăng kí
- [x] Xây dựng kế hoạch test trang Đăng kí
- [x] Viết test case giao diện trang Đăng kí

**Comment by truong-ne** [comment]
![Image](https://user-images.githubusercontent.com/118288031/230877644-360dc017-e161-43b9-88e8-b405afe45d66.png)
