### ISSUE TITLE
Viết test case cho trang Liên hệ

### ISSUE THREAD

**Issue by AnNgoIT** [AnNgoIT/Camera_Dashboard_Group03_TOEN#34]
- [x] Phân tích giao diện trang Liên hệ
- [x] Xây dựng kế hoạch test trang Liên hệ
- [x] Viết test case giao diện trang Liên hệ
- [x] Viết document cho các test case đã viết được

**Comment by tuannguyennocode** [comment]
Đã hoàn thành testcase cho trang liên hệ

**Comment by tuannguyennocode** [comment]
https://docs.google.com/document/d/1kZPZwBW-tW5v6XYAC-lkEdG8Rp563k21/edit?usp=sharing&ouid=105777061656077981289&rtpof=true&sd=true
