### ISSUE TITLE
Viết dàn ý đặc tả usercase

### ISSUE THREAD

**Issue by AnNgoIT** [AnNgoIT/Camera_Dashboard_Group03_TOEN#5]
- [x] Liệt kê đầy đủ các chức năng cần thiết của đề tài
- [x] Xác định yêu cầu của các chức năng 
- [x] Viết mô tả tổng quát về đề tài

**Comment by tuannguyennocode** [comment]
[Dàn ý đặc tả UserCase Part1.docx](https://github.com/AnNgoIT/Camera_Dashboard_Group03_TOEN/files/10993576/Dan.y.d.c.t.UserCase.Part1.docx)

**Comment by tuannguyennocode** [comment]
[Dàn ý đặc tả UserCase.docx](https://github.com/AnNgoIT/Camera_Dashboard_Group03_TOEN/files/11009060/Dan.y.d.c.t.UserCase.docx)
