### ISSUE TITLE
Deploy (CI/CD)

### ISSUE THREAD

**Issue by tuannguyennocode** [AnNgoIT/Camera_Dashboard_Group03_TOEN#66]
- [x] Nghiên cứu CI/CD cho project

- [x] Deploy

**Comment by AnNgoIT** [comment]
Đã nghiên cứu, và Deploy project trên môi trường AWS sử dụng Docker
Minh chứng: https://drive.google.com/drive/folders/12rMm2qt5ahXR_ZdVmqjr2_hhora8Q28r?usp=sharing
