### ISSUE TITLE
Vẽ usercase diagram cho toàn bộ các chức năng trên giao diện

### ISSUE THREAD

**Issue by AnNgoIT** [AnNgoIT/Camera_Dashboard_Group03_TOEN#8]
- [x] Dựa theo đặc tả đề tài, vẽ usercase diagram cho các chức năng
- [x] Sau khi các thành viên vẽ xong, meeting để chuẩn hóa lại bài làm theo đúng yêu cầu

**Comment by tuannguyennocode** [comment]
https://drive.google.com/file/d/1xtfITx21MXHdMlEMDffqtuHCatRj3nae/view?usp=share_link

**Comment by AnNgoIT** [comment]
https://drive.google.com/file/d/1sGZOIhaPaVqtsDp8VY10O51FrvqBYuD_/view?usp=sharing
